# Основные настройки Calamares для Vostok Linux
---
modules-search:
  - /usr/lib/calamares/modules
  - /usr/share/calamares/modules

# Определяем инстансы кастомных модулей
instances:
  - id:       postinstall
    module:   shellprocess
    config:   shellprocess_postinstall.conf

# Брендинг
branding: vostok
oem-setup: false

# Параметры интерфейса
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false

# Последовательность выполнения
sequence:
  # Этап показа (пользовательский ввод)
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - networkcfg
    - summary
  
  # Этап выполнения (установка)
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - xbpsinstall
    - packages
    - fstab
    - shellprocess@postinstall
    - bootloader
    - umount
  
  # Финальный этап
  - show:
    - finished