# Настройки клавиатуры
---
# Модель клавиатуры
model: pc105

# Основные раскладки
layouts:
  - us
  - ru

# Варианты раскладок
variants:
  - ""
  - ""

# Конфигурация X11
xOrgConfFileName: 00-keyboard.conf
xOrgConfXkbOptions: "grp:win_space_toggle"

# Консольная раскладка
convertKeyboard: true