# Настройки локали и времени
---
# Географические настройки
region: Europe
zone: Moscow

# Путь к locale.gen
localeGenPath: /etc/locale.gen

# Системная локаль по умолчанию
systemLocale: en_US.UTF-8

# Локали для генерации
locales:
  - en_US.UTF-8 UTF-8
  - ru_RU.UTF-8 UTF-8

# Дополнительные настройки
geoip:
  style: "json"
  url: "https://geoip.kde.org/v1/ubiquity"
  selector: "time_zone"