# Пост-установочные скрипты
---
# Выполнять в chroot окружении
dontChroot: false

# Таймаут выполнения (секунды)
timeout: 300

# Скрипты для выполнения
script:
  - "/var/lib/calamares/postinstall/post-install.sh"