# Распаковка файловой системы для Vostok Linux
# Проверь наличие файла в Live-сессии: ls /run/initramfs/live/LiveOS/
---
unpack:
  - source: "/run/initramfs/live/LiveOS/rootfs.img"
    sourcefs: "ext4"
    destination: ""
    weight: 60  # Процент прогресс-бара для этого шага
    # exclude:  # Опционально - что исключить из распаковки
    #   - /var/cache/xbps/*
    #   - /tmp/*
    #   - /root/.cache/*