# Настройки приветственного экрана
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false

# URL
supportUrl: https://vostoklinux.org/support
knownIssuesUrl: https://github.com/vostoklinux/issues
releaseNotesUrl: https://vostoklinux.org/release-notes/

# Требования к системе
requirements:
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
  
  # Минимальные требования
  requiredStorage: 20
  requiredRam: 2.0